[workspace]
resolver = "2"
members = [
    "core",
    "macros", 
    "cfgloader",
]
exclude = [
    "example"
]

[workspace.package]
authors = ["j50301m@yahoo.com.tw"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/YOUR_USERNAME/cfgloader_rs"


