[package]
name = "cfgloader"
version = "0.1.0"
edition = "2024"

[features]
default = ["derive"]
derive = ["macros"]

[dependencies]
core = { path = "../core" }

# Optional dependency on the derive macro
macros = { path = "../macros", optional = true }
