[package]
name = "cfgloader"
version = "0.1.0"
edition = "2024"

[features]
default = ["derive"]
derive = ["cfgloader-macros"]

[dependencies]
cfgloader-core = { path = "../cfgloader-core" }

# Optional dependency on the derive macro
cfgloader-macros = { path = "../cfgloader-macros", optional = true }
